### ISSUE TITLE
Questions about BIDS Labeling

### ISSUE THREAD

**Issue by mstraccia** [bids-standard/bids-specification#132] opened 2019-01-23 23:51 UTC
We are working on setting up BIDS formatting at UCLA. The goal is take the data directly from the scanner servers and move it either to a personal computer or our cluster and have the data in BIDS format with little effort on the users part. We have been taking our old script and modifying it to follow BIDS format. While we have been doing that, we ran into some questions that we did not know the answers to and though we should ask.

1) Where should the scouts files go and how should they be named?

2) This appears to be brought up in another post but it is not clear what the conclusion is. Our MPRAGE images come with NORMalized (intensity normalization performed by the scanner software) and original raw T1w scans. There seemed to be a suggestion to have _proc<label> identify it. What will the label be for the normalized and non-normalized images and will both or only one need that label?

3) When we have a study with multiple runs, we tend to name the BOLD scan in the scanner with either the same name (e.g. BOLD_AP and BOLD_AP) or by naming each run with a different name (e.g. BOLD_AP_Block01 and BOLD_AP_Block02). This might cause an issue when the code has to determine the run numbers itself if there are different naming conventions. This same issue applies to the task name (e.g. figuring out if it should be task-bold, task-rest, task-loc, etc). We would like to have our code be smart enough to automatically take the name of the run from the scanner and label it correctly in BIDS format. I assume it require everyone to change the name of their scan in the scanner for the BIDS script to work properly (unless there is a better way). Is there any agreement on what the names of the run in the scanner should be?

4) Relate to the previous issue, what happens if there is a run that was rerun and the first run's data should be discarded. This is could be because the trigger didn't catch, the code had to be restarted, or whatever. In an ideal world, the BIDS code could tell the same scan was run twice and name the second scan the normally and the first scan would have to have some sort of identifier saying this is a throw away scan. I assume this would require us to name each scan with a unique name (e.g. BOLD_AP_Block01 and BOLD_AP_Block02) so it can tell the same scan was ran twice. Has anyone else solved this issue?

5) This is more of a minor point but I know there is a push to no longer use the "subject" and instead use the term "participant". Unfortunately it seem the BIDS formatting uses sub everywhere. Do we have to use that naming convention? Is there another term we can use? Do scripts like fMRIPrep require sub term to be used?

**Comment by danlurie** [comment] 2019-01-24 05:42
Not sure what tool/script you’re using, but I’ve had good luck with [heudiconv](
https://github.com/nipy/heudiconv) to address two of these issues.

For cases where the same scan (e.g. a resting BOLD run) can have multiple possible names across sessions/studies (issue 3), it is possible to specify multiple heuristic rules to detect the same scan (e.g. one rule for each possible name or naming convention). Of course, this is only helpful insofar as you know what the possible set of names will be ahead of time. 

For scans that get re-run and should be discarded (issue 4), our lab has implemented a standard practice of appending “_XX” to the name of the DICOM folder for the scan to be discarded before the data is transferred to the server from the scanner. I then have a rule in the heuristic to ignore any scan with that suffix. As long as the rest of the heuristic checks match between the re-run(s) and the scan(s) to be ignored, heudiconv will then automatically number things properly and only consider the “good” scan(s).

Examples of logic for both of these things can be found in the [uc_bids.py heuristic](
https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/uc_bids.py).

**Comment by franklin-feingold** [comment] 2019-01-24 22:51
Hi @mstraccia,

Adding on to @danlurie's response 

1) The scout files are ignored because they are not in BIDS specification. You may place them under [`sourcedata`](https://bids-specification.readthedocs.io/en/v.1.1.2/02-common-principles.html#source-vs-raw-vs-derived-data)

2) For your raw scans, you can name them like you would typically following the specification. For your normalized you may add a proc since there has been something done to the image and this will help differentiate it from your actual raw scan. It is tricky because it is being processed and outputted directly from the scanner. This image could go into `sourcedata` as well if you are not going to be using the normalized scan.

3) I agree with Dan that heudiconv is a great tool for converting your files. If you have questions regarding running heudiconv, here is a [tutorial](http://reproducibility.stanford.edu/bids-tutorial-series-part-2a/).

4) Dan has a good strategy to approach this issue. Somehow identify it so your conversation tool (like heudiconv) can pick it up and ignore it for you.

5) Sub is how the specification has defined the naming structure. Tools like fMRIPrep assume your dataset is a validated BIDS set following that structure.

**Closed** 2019-04-06 07:14 UTC
Labels: question

**Comment by mstraccia** [comment] 2019-04-16 01:57
Thanks for both of your feedback!

This does open the door to a potential set of rules on how people should name their scans before they start their study. I assume most people name their scans without thinking much about it. If we want BIDS to be well adopted by a lot of groups, it needs to be as simple and "idiot proof" as possible. Heudiconv is usefully, however, the user has to upload a file to inform the code which scans are what. If there is an established convention on the name of the scan, there will be no need upload a file and it will make easier on the user.
