### ISSUE TITLE
licence annex link broken

### ISSUE THREAD

**Issue by CPernet** [bids-standard/bids-specification#1034] opened 2022-03-22 09:22 UTC
https://bids-specification.readthedocs.io/99-appendices/02-licenses.html is 404 - Not found

**Comment by sappelhoff** [comment] 2022-03-22 09:26
Thanks Cyril,

I am closing this as a duplicate of #1011 and #974 though :-)

We need to fix this asap ...

**Closed by sappelhoff** 2022-03-22 09:26 UTC
