### ISSUE TITLE
add subfields to authors in dataset_description.json

### ISSUE THREAD

**Issue by CPernet** [bids-standard/bids-specification#602] opened 2020-09-09 15:41 UTC
following a suggestion by @debruine in [psych-DS](https://github.com/psych-ds/psych-DS) we could have in [modality agnostic file](https://github.com/bids-standard/bids-specification/blob/master/src/03-modality-agnostic-files.md) an update of the dataset_description.json for authors, removing ambiguities. (not sure what this entail for the validator? as we should allow both types of entries)

```json
{
  "Name": "The mother of all experiments",
  "BIDSVersion": "1.4.0",
  "DatasetType": "raw",
  "License": "CC0",
  "Authors": [
  { "@type": "Person",
    "givenName": "Paul",
    "familyName": "Broca",
    "identifier": "https://orcid.org/0000-0000-0000-0001"},
  { "@type": "Person",
    "givenName": "Carl",
    "familyName": "Wernicke",
    "identifier": "https://orcid.org/0000-0000-0000-0002"}
],
  "Acknowledgements": "Special thanks to Korbinian Brodmann for help in formatting this dataset in BIDS. We thank Alan Lloyd Hodgkin and Andrew Huxley for helpful comments and discussions about the experiment and manuscript; Hermann Ludwig Helmholtz for administrative support; and Claudius Galenus for providing data for the medial-to-lateral index analysis.",
  "HowToAcknowledge": "Please cite this paper: https://www.ncbi.nlm.nih.gov/pubmed/001012092119281",
  "Funding": [
    "National Institute of Neuroscience Grant F378236MFH1",
    "National Institute of Neuroscience Grant 5RMZ0023106"
  ],
  "EthicsApprovals": [
    "Army Human Research Protections Office (Protocol ARL-20098-10051, ARL 12-040, and ARL 12-041)"
  ],
  "ReferencesAndLinks": [
    "https://www.ncbi.nlm.nih.gov/pubmed/001012092119281",
    "Alzheimer A., & Kraepelin, E. (2015). Neural correlates of presenile dementia in humans. Journal of Neuroscientific Data, 2, 234001. http://doi.org/1920.8/jndata.2015.7"
  ],
  "DatasetDOI": "10.0.2.3/dfjj.10",
  "HEDVersion": "7.1.1"
}
```
tagging @effigies @sappelhoff @robertoostenveld

**Comment by sappelhoff** [comment] 2020-09-09 16:16
I assume that the proposal only entails modifying the `Author` field? I didn't spot anything other that was different from what we currently support in BIDS.

re: the `Author` field --> that looks like an interesting direction to me

Currently, we say the following according to [this part of the spec](https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#dataset_descriptionjson):

> Authors: OPTIONAL. List of individuals who contributed to the creation/curation of the dataset.

Note that this is a little ambiguous and we could be a lot clearer in terms of what exact datatypes are expected. See this issue, where we want to start improving this state:

Looking at the validator schema however, we see that an "array of strings" is expected as input: see [link to validator code](https://github.com/bids-standard/bids-validator/blob/a6d9ada59b8628a52520bae96f5f45eb61f86a79/bids-validator/validators/json/schemas/dataset_description.json#L17-L22)

Now for the present proposal:

1. we would HAVE to keep allowing "array of strings" for backward compatibility
1. but we could add a second way to specify authors: "array of objects"
    1. where each "object" MUST have (and only have) the fields X, Y, Z (to be specified)

that wouldn't be a technical problem.

Overall I think this looks cool but it'd need a bit more tweaking (specify what other "@type" value you want to allow ... and why the `@` symbol is needed, then also what kind of "identifiers" would be permissible, etc.)

Let's hear what others have to say.

**Comment by effigies** [comment] 2020-09-09 17:12
cc @nellh It would be good to have an OpenNeuro perspective on this.

**Comment by satra** [comment] 2020-09-09 17:28
if anyone is interested here is the current version of the dataset contributor model we are using in DANDI.

https://github.com/dandi/dandi-cli/blob/c20d7888391c9abe6fdffbc53ea4e20f054bbde2/dandi/models.py#L510

which adds/overwrites the common model.
https://github.com/dandi/dandi-cli/blob/c20d7888391c9abe6fdffbc53ea4e20f054bbde2/dandi/models.py#L444

specifically this uses a field called contributor which can accept either a Person or an Organization as an object with specific roles assigned to these people.

this is not BIDS compatible, but should be compatible/translatable with datacite, which i believe is what openneuro uses for DOIs. although i don't know what pieces of metadata are transformed into the datacite model.

at present it seems that openneuro doi's provide some basic mapping to creator for all authors:

```
$ curl https://ez.datacite.org/id/doi:10.18112/openneuro.ds003105.v1.0.1
success: doi:10.18112/openneuro.ds003105.v1.0.1
_target: https://openneuro.org/datasets/ds003105/versions/1.0.1
datacite: <?xml version="1.0" encoding="UTF-8"?>%0A<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">%0A  <identifier identifierType="DOI">10.18112/OPENNEURO.DS003105.V1.0.1</identifier>%0A  <creators>%0A    <creator>%0A      <creatorName>Kelly Payette</creatorName>%0A    </creator>%0A    <creator>%0A      <creatorName>Andras Jakab</creatorName>%0A    </creator>%0A  </creators>%0A  <titles>%0A    <title xml:lang="en-us">Fetal Tissue Annotation Challenge FeTA Dataset</title>%0A  </titles>%0A  <publisher>Openneuro</publisher>%0A  <publicationYear>2020</publicationYear>%0A  <resourceType resourceTypeGeneral="Dataset">fMRI</resourceType>%0A</resource>
_profile: datacite
_datacenter: SUL.OPENNEURO
_export: yes
_created: 1598878722
_updated: 1598878724
_status: public
```

**Comment by ericearl** [comment] 2023-06-20 14:29
I know this is an old thread, but I was re-introduced to it today by @agt24. I think it would be great to NOT change the `dataset_description.json`'s `"Authors"` field, but instead accept EITHER:

1. The `"Authors"` field as-is in the `dataset_description.json` ; OR
2. A `CITATION.cff` file at the root level of the data set in lieu of a `dataset_description.json`'s `"Authors"` field since `CITATION.cff` is an accepted widespread standard of documenting details about authors.

Further reading:
- Their documentation website, https://citation-file-format.github.io/
- They even have a user-friendly tool to create one! https://citation-file-format.github.io/cff-initializer-javascript/#/

**Comment by ericearl** [comment] 2023-06-20 14:31
To clarify why I said "in lieu of", I meant if a CITATION.cff file is present, then the Authors field should not be included so there is no confusion or conflict of Authors.

**Comment by effigies** [comment] 2023-06-20 17:07
@ericearl That's a great idea! +1 from me.

**Comment by Remi-Gau** [comment] 2023-06-20 17:09
See also this issue: https://github.com/bids-standard/bids-specification/issues/901

**Comment by ericearl** [comment] 2023-06-20 17:15
Thank you for your rich historical memory @Remi-Gau! I'll go put a supporting comment there.

**Comment by effigies** [comment] 2023-06-20 17:49
@Remi-Gau It just sounds better when Eric says it...

**Comment by effigies** [comment] 2023-06-20 18:31
Let's consolidate discussion in #901. If there are points brought up here that need to be copied, please feel free to reproduce them there.

**Closed by effigies** 2023-06-20 18:31 UTC
