### ISSUE TITLE
Number sections

### ISSUE THREAD

**Issue by guiomar** [bids-standard/bids-specification#656] opened 2020-10-27 14:49 UTC
Hi! 

I think that numbering sections and subsections through out the specification will help to get a clearer global schema overview of the content and will facilitate reading. What do you think?

**Comment by effigies** [comment] 2020-10-27 14:58
Duplicate of #421.

@nicholst made an attempt at this in #454, but it turned out to be more difficult than expected.

**Comment by guiomar** [comment] 2020-10-27 15:01
Sorry for the duplicate! Thanks for linking it :)

**Closed** 2020-10-27 15:03 UTC
